### ISSUE TITLE
Parameter Conversion Errors: when Running  C++ Code with igraph, PCL on Windows

### ISSUE THREAD

**Issue by Rusullhu** [zhangxy0517/3D-Registration-with-Maximal-Cliques#40]
Hello, thanks for your valuable work!

I'm currently working with the PCL version 1.11.1 and Boost version 1.7.4 and  igraph 0.10.1 on a Windows environment while running the C++ code provided by the author on GitHub.  I'm encountering compatibility issues and require assistance to resolve them. If this is a version issue or something else. Any insights would be greatly helpful to me.

Here are the specific errors I'm encountering while running the  code:

```
Error E0167:
Description: Incompatibility between arguments of type "igraph_vector_t *" and type "igraph_vector_int_t *"
Project: Author's Code
File: [PCR.cpp]
Line: [509]  igraph_get_edgelist(g, &el, 0);

Error E0312:
Description: No user-defined conversion from "boost::shared_ptr[pcl::PointIndices](javascript:void(0))" to "pcl::PointIndicesPtr" exists
Severity: Error
Code: E0312
Project: Trial
File: desc_dec.cpp
Line: 706  pcl::PointIndicesPtr Idx = boost::shared_ptr<pcl::PointIndices>();

Error C2664:
Description: Cannot convert parameter 2 from "igraph_vector_t *" to "igraph_vector_int_t *"
Function: igraph_get_edgelist(const igraph_t *, igraph_vector_int_t *, igraph_bool_t)
Project: Author's Code
File: [PCR.cpp]
Line: [509]  igraph_get_edgelist(g, &el, 0);

Error C2664:
Description: Cannot convert parameter 2 from "igraph_vector_ptr_t *" to "igraph_vector_int_list_t *"
Function: igraph_maximal_cliques(const igraph_t *, igraph_vector_int_list_t *, igraph_integer_t, igraph_integer_t)
File: [registration.cpp]
Line: [757and 1238]  igraph_maximal_cliques(&g, &cliques, 3, 0); //3dlomatch 4 3dmatch; 3 Kitti  4 

```
I would like to request your assistance in understanding and resolving these issues while running the code provided by the author. Any guidance or suggestions would be greatly appreciated. Thank you for your help.

Best regards
![Error detail](https://github.com/zhangxy0517/3D-Registration-with-Maximal-Cliques/assets/106533748/26cbbdb7-c213-48d3-bc4a-d1a286ef9e3d)

**Comment by Rusullhu** [comment]
the problem is the version of igraph ,it should be 0.9.9
